baseurl: "http://zhezhang.co"
languageCode: "en-us"
title: "Zhe Zhang"
theme: "slim"
permalinks:
  post: /:year/:month/:slug/
paginate: 10

params:
  Subtitle: "Product Designer / Front-end Developer"
  GithubID: "zhe"
  TwitterID: "neomana"
  AnalyticsID: "UA-58516870-1"
