---
title: Zhe Zhang
theme: slim
sitemap:
  ChangeFreq: ''
  Priority: "-1"
  Filename: sitemap.xml
pluralizelisttitles: false
permalinks:
  post: "/:year/:month/:slug/"
languagecode: en-us
baseurl: http://zhezhang.co
params:
  analyticsid: UA-58516870-1
  githubid: zhe
  subtitle: Product Designer / Front-end Developer
  twitterid: neomana
