name = "Slim"
author = "Zhe Zhang"
description = "A slim minimal theme for Hugo."
license = "MIT"
source_repo = "https://github.com/zhe/hugo-theme-slim"
tags = ["minimal", "clean", "neat"]

[author]
  name = "Zhe Zhang"
  homepage = "http://zhezhang.co"
[params]
  Subtitles = "sssssSpinning the cogs in the widgets"
  GitHubUser = "sssspf13"
